export const postConstants = {
  SET_SELECTED_SORT: "SET_SELECTED_SORT",
  SET_ALL_POSTS: "SET_ALL_POSTS",
  HANDLE_LIKE_POST: "HANDLE_LIKE_POST",
  HANDLE_DISLIKE_POST: "HANDLE_DISLIKE_POST",
  CREATE_POST: "CREATE_POST",
  SET_SHOW_ADD_NEW_POST_MODAL: "SET_SHOW_ADD_NEW_POST_MODAL",
  DELETE_POST: "DELETE_POST",
  EDIT_POST: "EDIT_POST",
  UPDATED_POSTS: "UPDATED_POSTS",
};
