export const userConstants = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_BOOKMARKS: "GET_ALL_BOOKMARKS",
  ADD_TO_BOOKMARKS: "ADD_TO_BOOKMARKS",
  REMOVE_FROM_BOOKMARKS: "REMOVE_FROM_BOOKMARKS",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
  SET_SINGLE_USER: "SET_SINGLE_USER",
  SET_SHOW_EDIT_PROFILE_MODAL: "SET_SHOW_EDIT_PROFILE_MODAL",
  EDIT_USER_PROFILE: "EDIT_USER_PROFILE",
  SET_SHOW_AVATAR_MODAL: "SET_SHOW_AVATAR_MODAL",
  SET_SHOW_SEARCH_RESULTS: "SET_SHOW_SEARCH_RESULTS",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
};
