export const userConstants = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_BOOKMARKS: "GET_ALL_BOOKMARKS",
  ADD_TO_BOOKMARKS: "ADD_TO_BOOKMARKS",
  REMOVE_FROM_BOOKMARKS: "REMOVE_FROM_BOOKMARKS",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
  SET_SINGLE_USER: "SET_SINGLE_USER",
};
